version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: Mayyeutao0?
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:Mayyeutao0?@db:5432/postgres
      - SECRET_KEY=hZKxcKs2I92_s90ZVQNw4MF3BI1qKFFI-2PwhK8OlRM
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - RUN_MIGRATIONS=true
      - SEED_DATA=true
      - ADDITIONAL_CORS_ORIGINS=http://frontend:3000,http://localhost:3000
      - LM_STUDIO_BASE_URL=http://host.docker.internal:1234/v1
      - LM_STUDIO_MODEL=deepseek-r1-distill-qwen-1.5b
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - app_uploads:/app/uploads
      # Thêm volume mount cho development để dễ cập nhật code
      # - ./app:/app/app
      # - ./alembic:/app/alembic
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_SERVER_API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - app_uploads:/app/public/uploads
      # Thêm volume mount cho development để dễ cập nhật code
      # - ./frontend/app:/app/app
      # - ./frontend/components:/app/components
      # - ./frontend/lib:/app/lib

volumes:
  postgres_data:
  app_uploads:
